replicaCount: 1

image:
  repository: oryd/hydra
  pullPolicy: IfNotPresent
  tag: "v2.2.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  public:
    enabled: true
    type: ClusterIP
    port: 4444
    name: http
    annotations: {}
  admin:
    enabled: true
    type: ClusterIP
    port: 4445
    name: http
    annotations: {}

deployment:
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 5
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 5

secretAnnotations:
  # Create the secret before installation, and only then. This saves the secret from regenerating during an upgrade
  # pre-upgrade is needed to upgrade from 0.7.0 to newer. Can be deleted afterwards.
  helm.sh/hook-weight: "0"
  helm.sh/hook: "pre-install, pre-upgrade"
  helm.sh/hook-delete-policy: "before-hook-creation"
  helm.sh/resource-policy: "keep"

hydra:
  config:
    dsn: "postgresql://postgres:pgpassword@pg-minikube-postgresql.default.svc.cluster.local:5432/postgres"
    urls:
      self:
        issuer: "http://127.0.0.1:4444"
      login: https://devauth.baara.co/auth
      consent: http://127.0.0.1:3000/consent
      logout: http://127.0.0.1:3000/logout
      error: http://127.0.0.1:3000/error
  dev: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
