apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    {{- with .Values.secretAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  secretsSystem: {{ ( randAlphaNum 32 ) | required "Value secrets.system can not be empty!" | b64enc | quote }}
  secretsCookie: {{ ( randAlphaNum 32 ) | required "Value secrets.cookie can not be empty!" | b64enc | quote }}
  dsn: {{ include "hydra.dsn" . | b64enc | quote }}